name: Griffey
favicon: null
layout_spectrum: 1
typography_spectrum: 0.40744
title: Griffey the cat
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bcd4f7'
    - '#7aa660'
    - '#840309'
    - '#010101'
    - '#0a24f8'
  brandStrength: 1
  lightness: 0.25
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
