name: Griffey
favicon: null
layout_spectrum: 0.49787
typography_spectrum: 0.40744
title: Griffey the cat
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f55b4'
    - '#ffffff'
    - '#1ea28a'
    - '#82d8f9'
    - '#8b6d80'
  brandStrength: 0.5625
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 0
purpose: []
