name: Griffey
favicon: null
layout_spectrum: 1
typography_spectrum: 0.40744
title: Griffey the cat
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#614b00'
    - '#ceb805'
    - '#99880a'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.0625
  rhythmicContrast: 1
purpose: []
