name: Griffey
favicon: null
layout_spectrum: 0.65509
typography_spectrum: 0.40744
title: Griffey the cat
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f8edcd'
    - '#b266ba'
    - '#76e953'
    - '#26a6b9'
    - '#2e261d'
  brandStrength: 0.5625
  lightness: 0.625
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
